GET {{base}}/api/applications
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVhZThuSENxTV9jRjNkRDRmZjdhRiJ9.eyJpc3MiOiJodHRwczovL2VmdW5kenotY3JtLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJoeENKVkF3RVVpc1FwZ2Y1b0xNMmtnTVVwWGxUbzY4bEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hcGkuY3JtLmVmdW5kenouY29tIiwiaWF0IjoxNjg5NTQyMTMwLCJleHAiOjE2ODk2Mjg1MzAsImF6cCI6Imh4Q0pWQXdFVWlzUXBnZjVvTE0ya2dNVXBYbFRvNjhsIiwic2NvcGUiOiJyZWFkOnJvYm9sb2Fuel9hcHBsaWNhdGlvbnMiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJwZXJtaXNzaW9ucyI6WyJyZWFkOnJvYm9sb2Fuel9hcHBsaWNhdGlvbnMiXX0.l6oXLgaFx9-6SmDMQ6zp2uSRFPYEAHhdYDUDpYhY41yZfdkfM-BUSh1SNsS3yQ7xqtSDirqKrz6cYX74MBCOizyHuHYSp1MHzYsj2JlX3PlMlqd3f6omXH-P7KYmN8bTxgxc8nMZULiX2EX6jWYJlmfExMV31PP5gDIQfqIreDKiyeXJx7dkB9KIlpg0OeBfP7EqY8I9G7r3w3EgQXl8KrHUOM2sMkTJNAGpfCPh7Q8qXHXbNt9uuVidX390SXiKQf2uA9SzC5Y3tJrJH5ag7QJ22d9yeZ-ok622SC_Rwvx3SHzpVGqXqWgG9GEWLUywmVeL3TEhdY7W4_J00VcSHA