GET http://localhost:8081/api/applications
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9jcm0tZWZ1bmR6ei5ldS5hdXRoMC5jb20vIn0..muxL_S5LLDSLEZFK.k3ho8sDgsooakYzgKsMclsfl5P9aBVZDxC6GCmgNC1TAH7h5UqD0fg7zszEptezbCsb3_nQmLqlC25UF2tPo1aAZVKN2JGpf2sm2ZuRlaVyOsgcZ65V-aMmiWaeZF85ePfw1FDPg2mALeooJV3cnBZngjoZkIc-gaNLspK5M7uAhvIGz59jydG67w129nXMR7wna5rASRblW3dhmoW-ScoRG4L1uyk4CRa6GlOxjV3zW5HIRorpOleIAiCXNn73skkez5zlC5anBXcVJ14UMF-L_6Pe1--G6O4l7P-fbumxc57Liilox6oMeGZfNEGf9.pPqHnEcYhQ-o-DyFlh-Z6A