GET http://localhost:8081/api/applications
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjR2WVFZcjB3a0JIUy14Y21leE1HMSJ9.eyJpc3MiOiJodHRwczovL2NybS1lZnVuZHp6LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJsTFVQcDRtQ09WVGlVamxFdVBuZ0dwMUowYkhkVnpsU0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hcGkuY3JtLWRldi5lZnVuZHp6LmNvbSIsImlhdCI6MTY4OTExNTU5OSwiZXhwIjoxNjg5MjAxOTk5LCJhenAiOiJsTFVQcDRtQ09WVGlVamxFdVBuZ0dwMUowYkhkVnpsUyIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.j3ve_TNJNB9zYwkJIIPM-3Jwm0LolbPAMeDtZeohdWppkNWbmFExhZypxwe5MopiLayfgkWoqARffbcZfeZG2oTsKa-iPehnBy508LpGTCR8V6BR2mZllN-w7e4zhty0RQRhWEAI71ypIU2LWB8aNMrByfmuN1jwj4RT9qRa3LHB-nFg2ONiLl-cB0bgohnkLuqhqVSKsYU1qkACiAZcI98x2cu1_xRmw_U9tdfII0zhThiO0VLrs-3HDYuFJLyEdYJ66u1IeUbhyfcg-YpSCkDte63-GzOh2rNii9vPe2Mzp1GcN256yAghOsNSgnW4w5Gtxo7MBj5_5yezH7aaVA