debug: true
server:
  port: 8081

auth0:
  audience: https://api.crm-dev.efundzz.com
  domain: crm-efundzz.eu.auth0.com
  apiClientId: 3X7R1XdqDevXqVyXbt63lsoNm1ZZOjkF
  apiClientSecret: Y_KoJET9aauugxjZFDOTC5Ga7kbtKH8b2U4SapAZr4IzS0ciNQjUMf5j75G8PMfw
  connectionId: con_QKk7fMS7duEPvY4W
custom:
  duration:
      days: 180

spring:
  datasource:
    url: ${DATABASE_URI}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://crm-efundzz.eu.auth0.com/
excel:
  contentType: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

