debug: true
server:
  port: 8081

auth0:
  audience: https://api.crm-dev.efundzz.com

custom:
  duration:
      days: 180

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm-partner
    username: postgres
    password: Demo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://crm-efundzz.eu.auth0.com/
excel:
  contentType: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
